name: Code Style

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions: read-all

jobs:
  autoformat:
    name: Auto-format and Check
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        tool:
          - goimports
          - gofmt

        include:
        - tool: gofmt
          options: -s
        - tool: goimports
          importpath: golang.org/x/tools/cmd/goimports

    steps:
      - name: Set up Go 1.16.x
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 #v2.1.5
        with:
          go-version: 1.16.x
        id: go

      - name: Check out code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0

      - name: Install Dependencies
        if: ${{ matrix.importpath != '' }}
        run: |
          cd $(mktemp -d)
          GO111MODULE=on go get ${{ matrix.importpath }}

      - name: ${{ matrix.tool }} ${{ matrix.options }}
        shell: bash
        run: >
          ${{ matrix.tool }} ${{ matrix.options }} -w
          $(find .
          -path './vendor' -prune
          -o -path './third_party' -prune
          -o -name '*.pb.go' -prune
          -o -name 'wire_gen.go' -prune
          -o -type f -name '*.go' -print)

      - name: Verify ${{ matrix.tool }}
        shell: bash
        run: |
          # From: https://backreference.org/2009/12/23/how-to-match-newlines-in-sed/
          # This is to leverage this workaround:
          # https://github.com/actions/toolkit/issues/193#issuecomment-605394935
          function urlencode() {
            sed ':begin;$!N;s/\n/%0A/;tbegin'
          }
          if [[ $(git diff-index --name-only HEAD --) ]]; then
              for x in $(git diff-index --name-only HEAD --); do
                echo "::error file=$x::Please run ${{ matrix.tool }} ${{ matrix.options }}.%0A$(git diff $x | urlencode)"
              done
              echo "${{ github.repository }} is out of style. Please run ${{ matrix.tool }} ${{ matrix.options }}."
              exit 1
          fi
          echo "${{ github.repository }} is formatted correctly."
